# https://github.com/actions/labeler


Frontend:
  - "packages/ui/**"
  - "packages/react/**"
  - "apps/web/src/components/**"
  - "apps/web/src/app/**"

UI:
  - "packages/ui/**"

Backend:
  - "packages/api/**"

Database migration:
  - "packages/db/drizzle/migrations/**"

Database schema:
  - "packages/db/src/schema/**"

Infrastructure:
  - ".github/**"
  - ".husky/**"

