services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-web
      args:
        - DATABASE_URL=${DATABASE_URL}
        - NEXT_PUBLIC_APP_URL=http://localhost:3000
        - NEXT_PUBLIC_WEBSOCKET_URL=http://localhost:4000
        - NODE_ENV=production
        - NEXT_PUBLIC_PACKAGE_ENV=production
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - OPEN_AI_MODEL=${OPEN_AI_MODEL}
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
        - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
        - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
        - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
        - NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NEXT_PUBLIC_WEBSOCKET_URL=http://localhost:4000
      - NODE_ENV=production
      - NEXT_PUBLIC_PACKAGE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPEN_AI_MODEL=${OPEN_AI_MODEL}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
      - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
      - NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    volumes:
      - web_next_cache:/app/apps/web/.next

  websocket-server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-websocket-server
    ports:
      - "4000:4000"
    environment:
      - NEXT_PUBLIC_APP_URL=http://web:3000
      - NODE_ENV=production
    depends_on:
      - web

volumes:
  web_next_cache: