packages:
  - "apps/*"
  - "packages/*"


# Define a catalog of version ranges.
catalog:
  react: 19.1.0
  react-dom: 19.1.0
  zod: ^3.25.76
  next: 15.3.0
  typescript: 5.8.3
  bun: 1.2.10
  "@types/react": 19.1.2
  "@types/react-dom": 19.1.2
  "@types/node": ^22
  "ai": "5.0.5"
  "@ai-sdk/openai": "2.0.0"
  "@ai-sdk/react": "2.0.28"