packages:
  - "apps/*"
  - "packages/*"


# Define a catalog of version ranges.
catalog:
  react: 19.1.0
  react-dom: 19.1.0
  zod: 4.1.11
  next: 15.5.4
  typescript: 5.8.3
  bun: 1.2.10
  ai: "5.0.5"
  "@ai-sdk/openai": "2.0.0"
  "@ai-sdk/react": "2.0.28"
  posthog-node: 5.9.1
  "@hookform/resolvers": "5.2.2"
  react-hook-form: "7.63.0"
  "@types/react": 19.1.2
  "@types/react-dom": 19.1.2
  "@types/node": ^22
  