name: 💡 Features & Ideas
description: Describe a new feature or capability you would like to see in ConvoForm.
labels:
  - Feature request
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome 👋🏻

        Thank you for taking the time to write up a feature request. Please fill out the information below to be able to help you faster. If you have a question or need general help, please join our [Discord community](https://discord.gg/aeYtKyn2E2).
  - type: textarea
    attributes:
      label: Description
      description:
        Describe the feature or capability you would like to see in OpenStatus'
        offering.
      placeholder:
        Make sure it's unique, describe your use case, and explain the problem
        and proposed solution.
    validations:
      required: true
    
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/growupanand/ConvoForm/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to be friendly and polite to people in this repository
          required: true
        - label: "I want to work on this issue and already read the [Contributing Guidelines](https://github.com/growupanand/ConvoForm/blob/main/CONTRIBUTING.md)"
          required: false